import sqlmodel
"""crear tabla cliente y servicio

Revision ID: acf9d5339f46
Revises: fa997ff8cbf5
Create Date: 2026-10-02 20:14:37.440336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acf9d5339f46'
down_revision: Union[str, Sequence[str], None] = 'fa997ff8cbf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
