import sqlmodel
"""crear tabla cliente y servicio

Revision ID: f13172a690f6
Revises: acf9d5339f46
Create Date: 2026-10-02 20:24:12.100015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f13172a690f6'
down_revision: Union[str, Sequence[str], None] = 'acf9d5339f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
